package github

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/go-github/v62/github"
	"go.uber.org/zap"
	"golang.org/x/oauth2"

	"codereviewagent/internal/errors"
)

type Client struct {
	gh  *github.Client
	log *zap.Logger
}

func NewClient(token string, log *zap.Logger) *Client {
	if token == "" {
		return &Client{log: log.Named("github")}
	}
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	tc := oauth2.NewClient(context.Background(), ts)
	return &Client{gh: github.NewClient(tc), log: log.Named("github")}
}

func (c *Client) Enabled() bool {
	return c != nil && c.gh != nil
}

func (c *Client) GetPRDiff(ctx context.Context, owner, repo string, prNumber int) (string, error) {
	if !c.Enabled() {
		return "", errors.WithMessage(errors.ErrInternal, "GitHub client is not configured")
	}

	c.log.Debug("listing PR files",
		zap.String("repo", owner+"/"+repo),
		zap.Int("pr", prNumber),
	)

	files, _, err := c.gh.PullRequests.ListFiles(ctx, owner, repo, prNumber, nil)
	if err != nil {
		c.log.Error("failed to list PR files",
			zap.String("repo", owner+"/"+repo),
			zap.Int("pr", prNumber),
			zap.Error(err),
		)
		return "", errors.WithCause(errors.ErrInternal, fmt.Errorf("list PR files: %w", err))
	}

	c.log.Debug("PR files listed",
		zap.String("repo", owner+"/"+repo),
		zap.Int("pr", prNumber),
		zap.Int("file_count", len(files)),
	)

	var b strings.Builder
	for _, f := range files {
		b.WriteString(fmt.Sprintf("--- %s (+%d/-%d)\n", f.GetFilename(), f.GetAdditions(), f.GetDeletions()))
		if f.Patch != nil {
			b.WriteString(*f.Patch)
			b.WriteString("\n")
		}
	}
	return b.String(), nil
}

func (c *Client) PostReviewComment(ctx context.Context, owner, repo string, prNumber int, body string) error {
	if !c.Enabled() {
		return errors.WithMessage(errors.ErrInternal, "GitHub client is not configured")
	}

	comment := &github.IssueComment{Body: github.String(body)}
	_, _, err := c.gh.Issues.CreateComment(ctx, owner, repo, prNumber, comment)
	if err != nil {
		c.log.Error("failed to create PR comment",
			zap.String("repo", owner+"/"+repo),
			zap.Int("pr", prNumber),
			zap.Error(err),
		)
		return errors.WithCause(errors.ErrInternal, fmt.Errorf("post PR comment: %w", err))
	}
	c.log.Info("PR comment created",
		zap.String("repo", owner+"/"+repo),
		zap.Int("pr", prNumber),
	)
	return nil
}

func BuildPRComment(overall int, summary string, findingsCount int, criticalCount int) string {
	var b strings.Builder
	b.WriteString("## 🤖 Code Review Agent Report\n\n")
	b.WriteString(fmt.Sprintf("**Overall Quality Score:** %d/100\n\n", overall))
	b.WriteString(fmt.Sprintf("**Summary:** %s\n\n", summary))
	b.WriteString(fmt.Sprintf("**Findings:** %d total", findingsCount))
	if criticalCount > 0 {
		b.WriteString(fmt.Sprintf(" (%d critical/high)", criticalCount))
	}
	b.WriteString("\n\n")
	b.WriteString("_Generated by Code Review Agent_\n")
	return b.String()
}
