package service

import (
	"context"
	"fmt"
	"strings"

	"codereviewagent/internal/errors"
	ghclient "codereviewagent/internal/github"
	"codereviewagent/internal/models"
	"codereviewagent/internal/reviewer"
)

type ReviewService struct {
	reviewer      reviewer.Reviewer
	github        *ghclient.Client
	postComments  bool
}

func NewReviewService(rev reviewer.Reviewer, gh *ghclient.Client, postComments bool) *ReviewService {
	return &ReviewService{
		reviewer:     rev,
		github:       gh,
		postComments: postComments,
	}
}

func (s *ReviewService) ReviewCode(ctx context.Context, req models.ReviewRequest) (*models.ReviewResult, error) {
	if strings.TrimSpace(req.Code) == "" {
		return nil, errors.WithMessage(errors.ErrInvalidRequest, "code cannot be empty")
	}
	return s.reviewer.ReviewCode(ctx, req.Code, req.Language, req.FilePath, req.Context)
}

func (s *ReviewService) ReviewPullRequest(ctx context.Context, owner, repo string, prNumber int) (*models.ReviewResult, error) {
	if !s.github.Enabled() {
		return nil, errors.WithMessage(errors.ErrInternal, "GitHub token is not configured")
	}

	diff, err := s.github.GetPRDiff(ctx, owner, repo, prNumber)
	if err != nil {
		return nil, err
	}
	if strings.TrimSpace(diff) == "" {
		return nil, errors.WithMessage(errors.ErrInvalidRequest, "pull request has no reviewable changes")
	}

	repoFullName := fmt.Sprintf("%s/%s", owner, repo)
	result, err := s.reviewer.ReviewDiff(ctx, diff, repoFullName, prNumber)
	if err != nil {
		return nil, err
	}

	if s.postComments {
		comment := buildDetailedPRComment(result)
		if postErr := s.github.PostReviewComment(ctx, owner, repo, prNumber, comment); postErr != nil {
			return result, postErr
		}
	}

	return result, nil
}

func (s *ReviewService) HandleWebhookPR(ctx context.Context, owner, repo string, prNumber int) (*models.ReviewResult, error) {
	return s.ReviewPullRequest(ctx, owner, repo, prNumber)
}

func buildDetailedPRComment(r *models.ReviewResult) string {
	var b strings.Builder
	b.WriteString("## 🤖 Code Review Agent Report\n\n")
	b.WriteString(fmt.Sprintf("**Overall Quality:** %d/100\n\n", r.Quality.Overall))
	b.WriteString(fmt.Sprintf("| Maintainability | Readability | Security | Performance |\n"))
	b.WriteString(fmt.Sprintf("|:---:|:---:|:---:|:---:|\n"))
	b.WriteString(fmt.Sprintf("| %d | %d | %d | %d |\n\n",
		r.Quality.Maintainability, r.Quality.Readability, r.Quality.Security, r.Quality.Performance))
	b.WriteString(fmt.Sprintf("**Summary:** %s\n\n", r.Quality.Summary))

	if len(r.Findings) > 0 {
		b.WriteString("### Findings\n\n")
		for i, f := range r.Findings {
			if i >= 15 {
				b.WriteString(fmt.Sprintf("\n_...and %d more findings_\n", len(r.Findings)-15))
				break
			}
			loc := ""
			if f.FilePath != "" {
				loc = fmt.Sprintf(" (`%s`", f.FilePath)
				if f.Line > 0 {
					loc += fmt.Sprintf(":%d", f.Line)
				}
				loc += ")"
			}
			b.WriteString(fmt.Sprintf("- **[%s/%s]** %s%s: %s\n",
				strings.ToUpper(string(f.Severity)), f.Category, f.Title, loc, f.Description))
			if f.Suggestion != "" {
				b.WriteString(fmt.Sprintf("  - 💡 _Suggestion:_ %s\n", f.Suggestion))
			}
		}
		b.WriteString("\n")
	}

	if len(r.Strengths) > 0 {
		b.WriteString("### Strengths\n\n")
		for _, s := range r.Strengths {
			b.WriteString(fmt.Sprintf("- ✅ %s\n", s))
		}
		b.WriteString("\n")
	}

	if len(r.Suggestions) > 0 {
		b.WriteString("### Suggestions\n\n")
		for _, s := range r.Suggestions {
			b.WriteString(fmt.Sprintf("- %s\n", s))
		}
		b.WriteString("\n")
	}

	b.WriteString("_Generated by Code Review Agent_\n")
	return b.String()
}
